#!/bin/bash
#
#   Issue #1 - Sending interrupt does not interrupt
#


silk server --tcp=3200 &
server=$!

dir="$(mktemp -d --suffix='.d' 'test.XXXXXX')"

atexit() {
    rm -rf "${dir}"
    kill ${server} 2> '/dev/null'
    kill ${client} 2> '/dev/null'
}

trap atexit 'EXIT'


printf "#!/bin/bash\ntouch '${dir}/go'\nsleep 60\ntrue\n" \
    | silk run -L localhost:3200 - &
client=$!

# Wait for the remote command to start
while ! [ -e "${dir}/go" ] ; do
    sleep 0.01
done

/usr/bin/kill -INT ${client}

# Wait for the remote command to get signaled
sleep 0.1

# Test if the process terminated correctly
! ps --no-headers ${client}
