#!/bin/bash
#
#   Is a remote server able to delete stored keys?
#


silk server --tcp=3200 --pidfile='silk.pid' &
while [ ! -e 'silk.pid' ] ; do sleep 0.01 ; done

silk kv 'localhost:3200' a=foo b= c=bar

silk kv --delete 'localhost:3200' a c

silk kv 'localhost:3200' > 'observed'

grep '^b$' 'observed'
