#!/bin/bash
#
#   Can a remote server run a command with text substitution?
#


silk server --tcp=3200 &

silk kv 'localhost:3200' id=17

silk run 'localhost:3200' echo 'My ID is "%{id}"' > 'observed'

cat > 'expected' <<EOF
My ID is "17"
EOF

diff -Naur 'observed' 'expected'
