#!/bin/bash
#
#   Does the client exit with failure if the remote processes fails?
#


silk server --tcp=3200 --pidfile='silk.pid' &
while [ ! -e 'silk.pid' ] ; do sleep 0.01 ; done

silk run 'localhost:3200' false
ret=$?

test ${ret} -ne 0
