#!/bin/bash
#
#   Does the client exit with failure if at least one remote processe fails?
#


silk server --tcp=3200 --pidfile='a.pid' &
silk server --tcp=3201 --pidfile='b.pid' &
while [ ! -e 'a.pid' -o ! -e 'b.pid' ] ; do sleep 0.01 ; done

silk kv 'localhost:3200' val=0
silk kv 'localhost:3201' val=1

silk run '(localhost:3200|localhost:3201)' test '%{val}' -eq 0
ret=$?

test ${ret} -ne 0
