#!/bin/bash
#
#   Can a remote server execute a command in a given working directory
#   specified by environment variable?
#


silk server --tcp=3200 &

mkdir 'dir'
mkdir 'dir/cwd'
touch 'dir/cwd/a' 'dir/cwd/b'

export SILK_CWD='dir/cwd'
silk run 'localhost:3200' ls -1 > "observed"

cat > "expected" <<EOF
a
b
EOF

diff -Naur "observed" "expected"
